name: Deploy Tic-tac-toe application.
on:
    push:
        branches: [main]
        #paths: ['client/**']
    pull_request:
        branches: [main]
        #paths: ['client/**']

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    # Single deploy job since we're just deploying
    deploy:
        runs-on: ubuntu-latest
        env:
            working-directory: ./client
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
            
            -   name: npm ci, build and test
                working-directory: ${{ env.working-directory }}

                run: |
                    npm ci 
                    npm run build
                    npm test

            -   name: Setup Pages
                uses: actions/configure-pages@v3

            -   name: Upload artifact
                uses: actions/upload-pages-artifact@v1
                with:
                    # Upload entire repository
                    path: "./client/dist/*"

            -   name: Deploy to GitHub Pages
                id: deployment
                uses: actions/deploy-pages@v2
