name: Deploy Tic-tac-toe application.
on:
    push:
        branches: [main]
        paths: ['client/**']
    pull_request:
        branches: [main]
        paths: ['client/**']

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
    contents: read
    pages: write
    id-token: write

concurrency:
    group: "pages"
    cancel-in-progress: false

jobs:
    # Single deploy job since we're just deploying
    deploy:
        runs-on: ubuntu-latest
        env:
            working-directory: ./client
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
            
            -   name: npm ci, build and test
                working-directory: ${{ env.working-directory }}

                run: |
                    npm ci 
                    npm run build
                    npm test
            -   name: Deploy
                working-directory: ${{ env.working-directory }}
                run: |
                    git config --global user.name 'EdCrux'
                    git config --global user.email 'jecruxiz@gmail.com'
                    git remote set-url origin https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/${{ github.repository }}    
                    npm run deploy
