name: Deploy react Tic-tac-toe application
on:
    push:
        branches: [main]
        #paths: ['client/**']
    pull_request:
        branches: [main]
        #paths: ['client/**']

jobs:
    build_test:
        runs-on: ubuntu-latest
        env:
            working-directory: ./client

        strategy:
            matrix: 
                node-version: [18.x]

        steps:
            -   uses: actions/checkout@v2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}

            -   name: npm ci, build and test
                working-directory: ${ env.working-directory }}

                run: |
                    npm ci --only=prod
                    npm run build --if-present
                    npm test
            -   name: deploy to gh-pages
                uses: peaceiris/actions-gh-pages@v3
                with:
                    deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                    publish_dir: ./build          
